import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
	HydrationBoundary,
	QueryClient,
	dehydrate,
} from "@tanstack/react-query";
import { getProfile } from "./(api)/profile";
import { getAccessToken } from "./(api)/auth/tokens";
import { TanstackProvider } from "./TanstackProvider";
import { ManifestAssets } from "./assets/pwa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// if we're logged in, prefetch data we need on every page
	const queryClient = new QueryClient();
	const accessToken = await getAccessToken();
	if (accessToken) {
		await queryClient.prefetchQuery({
			queryKey: ["getMe"],
			queryFn: getProfile,
		});
	}

	return (
		<html lang="en">
			<ManifestAssets />
			<body className={inter.className}>
				<TanstackProvider>
					<HydrationBoundary state={dehydrate(queryClient)}>
						{children}
					</HydrationBoundary>
				</TanstackProvider>
			</body>
		</html>
	);
}
