name: build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile
      - run: timeout 12s bun lint || bun lint # Workaround for Windows compatibility
      - run: bun test
      - run: ./scripts/check-lines.sh
      - run: bun ./scripts/check-bundle-size.ts
